name: Go CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: macos-latest

    strategy:
      matrix:
        go-version: [ '1.17.x', '1.18.x', '1.19.x' ]

    steps:
    - uses: actions/checkout@v2
    - name: Setup Go environment
      uses: actions/setup-go@v2
      with:
        go-version: ${{ matrix.go-version }}
        check-latest: false
    - name: lint
      run: |
        GO111MODULE=off GOBIN=$(pwd)/bin go get golang.org/x/lint/golint
        bin/golint -set_exit_status ./...
      if: "matrix.os == 'ubuntu-latest' || matrix.os == 'macOS-latest'"
    - name: Print Go version
      run: go version
    - name: Build
      run: go build -v ./...
    - name: Run tests
      run: go test -v ./...
    - name: Run linter
      run: golangci-lint run
