name: Go CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: macos-latest

    strategy:
      matrix:
        go-version: [ '1.17.x', '1.18.x', '1.19.x' ]

    steps:
    - uses: actions/checkout@v2
    - name: Setup Go environment
      uses: actions/setup-go@v2
      with:
        go-version: ${{ matrix.go-version }}
        check-latest: false
    - name: Install golangci-lint
      run: go install github.com/golangci/golangci-lint/cmd/golangci-lint@latest
    - name: Print Go version
      run: go version
    - name: Build
      run: go build -v ./...
    - name: Run tests
      run: go test -v ./...
    - name: Run linter
      run: golangci-lint run
